spring:
  application:
    name: gestion-proyectos

  datasource:
    url: jdbc:postgresql://localhost:5432/taskforge
    username: taskforge_user
    password: taskforge_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080